WebApp/Controllers/InfoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DAL.App.EF;
using Domain;
using DAL.App.Interfaces;

namespace WebApp.Controllers
{
    public class InfoController : Controller
    {
        private readonly IAppUnitOfWork _uow;

        public InfoController(IAppUnitOfWork uow)
        {
            _uow = uow;
        }

        // GET: Info
        public async Task<IActionResult> Index()
        {
            //var applicationDbContext = _uow.Info.Include(i => i.Campaign).Include(i => i.Cinema).Include(i => i.Discount).Include(i => i.DiscountType).Include(i => i.InfoType).Include(i => i.Movie).Include(i => i.Product).Include(i => i.UserGroup);
            return View(await _uow.Info.AllAsync());
        }

        // GET: Info/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var info = await _uow.Info.FindAsync(id);
                //.Include(i => i.Campaign)
                //.Include(i => i.Cinema)
                //.Include(i => i.Discount)
                //.Include(i => i.DiscountType)
                //.Include(i => i.InfoType)
                //.Include(i => i.Movie)
                //.Include(i => i.Product)
                //.Include(i => i.UserGroup)
                //.SingleOrDefaultAsync(m => m.InfoId == id);
            if (info == null)
            {
                return NotFound();
            }

            return View(info);
        }

        // GET: Info/Create
        public async Task<IActionResult> Create()
        {
            //ViewData["CampaignId"] = new SelectList(_uow.Campaigns, "CampaignId", "CampaignName");
            //ViewData["CinemaId"] = new SelectList(_uow.Cinemas, "CinemaId", "Address");
            //ViewData["DiscountId"] = new SelectList(_uow.Discounts, "DiscountId", "DisccountName");
            //ViewData["DiscountTypeId"] = new SelectList(_uow.DiscountTypes, "DiscountTypeId", "DiscountTypeName");
            //ViewData["InfoTypeId"] = new SelectList(_uow.InfoTypes, "InfoTypeId", "InfoTypeName");
            //ViewData["MovieId"] = new SelectList(_uow.Movies, "MovieId", "MovieName");
            //ViewData["ProductId"] = new SelectList(_uow.Products, "ProductId", "ProductName");
            //ViewData["UserGroupId"] = new SelectList(_uow.UserGroups, "UserGroupId", "UserGroupName");
            ViewData["CampaignId"] = new SelectList(await _uow.Campaigns.AllAsync(), nameof(Campaign.CampaignId), nameof(Campaign.CampaignName));
            ViewData["CinemaId"] = new SelectList(await _uow.Cinemas.AllAsync(), nameof(Cinema.CinemaId), nameof(Cinema.CinemaName));
            ViewData["DiscountId"] = new SelectList(await _uow.Discounts.AllAsync(), nameof(Discount.DiscountId), nameof(Discount.DisccountName));
            ViewData["DiscountTypeId"] = new SelectList(await _uow.DiscountTypes.AllAsync(), nameof(DiscountType.DiscountTypeId), nameof(DiscountType.DiscountTypeName));
            ViewData["InfoTypeId"] = new SelectList(await _uow.InfoTypes.AllAsync(), nameof(InfoType.InfoTypeId), nameof(InfoType.InfoTypeName));
            ViewData["MovieId"] = new SelectList(await _uow.Movies.AllAsync(), nameof(Movie.MovieId), nameof(Movie.MovieName));
            ViewData["ProductId"] = new SelectList(await _uow.Products.AllAsync(), nameof(Product.ProductId), nameof(Product.ProductName));
            ViewData["UserGroupId"] = new SelectList(await _uow.UserGroups.AllAsync(), nameof(UserGroup.UserGroupId), nameof(UserGroup.UserGroupName));

            return View();
        }

        // POST: Info/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("InfoId,Description,InfoTypeId,CinemaId,MovieId,ProductId,CampaignId,UserGroupId,DiscountId,DiscountTypeId")] Info info)
        {
            if (ModelState.IsValid)
            {
                _uow.Info.Add(info);
                await _uow.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            //ViewData["CampaignId"] = new SelectList(_uow.Campaigns, "CampaignId", "CampaignName", info.CampaignId);
            //ViewData["CinemaId"] = new SelectList(_uow.Cinemas, "CinemaId", "Address", info.CinemaId);
            //ViewData["DiscountId"] = new SelectList(_uow.Discounts, "DiscountId", "DisccountName", info.DiscountId);
            //ViewData["DiscountTypeId"] = new SelectList(_uow.DiscountTypes, "DiscountTypeId", "DiscountTypeName", info.DiscountTypeId);
            //ViewData["InfoTypeId"] = new SelectList(_uow.InfoTypes, "InfoTypeId", "InfoTypeName", info.InfoTypeId);
            //ViewData["MovieId"] = new SelectList(_uow.Movies, "MovieId", "MovieName", info.MovieId);
            //ViewData["ProductId"] = new SelectList(_uow.Products, "ProductId", "ProductName", info.ProductId);
            //ViewData["UserGroupId"] = new SelectList(_uow.UserGroups, "UserGroupId", "UserGroupName", info.UserGroupId);
            ViewData["CampaignId"] = new SelectList(await _uow.Campaigns.AllAsync(), nameof(Campaign.CampaignId), nameof(Campaign.CampaignName));
            ViewData["CinemaId"] = new SelectList(await _uow.Cinemas.AllAsync(), nameof(Cinema.CinemaId), nameof(Cinema.CinemaName));
            ViewData["DiscountId"] = new SelectList(await _uow.Discounts.AllAsync(), nameof(Discount.DiscountId), nameof(Discount.DisccountName));
            ViewData["DiscountTypeId"] = new SelectList(await _uow.DiscountTypes.AllAsync(), nameof(DiscountType.DiscountTypeId), nameof(DiscountType.DiscountTypeName));
            ViewData["InfoTypeId"] = new SelectList(await _uow.InfoTypes.AllAsync(), nameof(InfoType.InfoTypeId), nameof(InfoType.InfoTypeName));
            ViewData["MovieId"] = new SelectList(await _uow.Movies.AllAsync(), nameof(Movie.MovieId), nameof(Movie.MovieName));
            ViewData["ProductId"] = new SelectList(await _uow.Products.AllAsync(), nameof(Product.ProductId), nameof(Product.ProductName));
            ViewData["UserGroupId"] = new SelectList(await _uow.UserGroups.AllAsync(), nameof(UserGroup.UserGroupId), nameof(UserGroup.UserGroupName));
            return View(info);
        }

        // GET: Info/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var info = await _uow.Info.FindAsync(id);
            if (info == null)
            {
                return NotFound();
            }
            //ViewData["CampaignId"] = new SelectList(_uow.Campaigns, "CampaignId", "CampaignName", info.CampaignId);
            //ViewData["CinemaId"] = new SelectList(_uow.Cinemas, "CinemaId", "Address", info.CinemaId);
            //ViewData["DiscountId"] = new SelectList(_uow.Discounts, "DiscountId", "DisccountName", info.DiscountId);
            //ViewData["DiscountTypeId"] = new SelectList(_uow.DiscountTypes, "DiscountTypeId", "DiscountTypeName", info.DiscountTypeId);
            //ViewData["InfoTypeId"] = new SelectList(_uow.InfoTypes, "InfoTypeId", "InfoTypeName", info.InfoTypeId);
            //ViewData["MovieId"] = new SelectList(_uow.Movies, "MovieId", "MovieName", info.MovieId);
            //ViewData["ProductId"] = new SelectList(_uow.Products, "ProductId", "ProductName", info.ProductId);
            //ViewData["UserGroupId"] = new SelectList(_uow.UserGroups, "UserGroupId", "UserGroupName", info.UserGroupId);
            ViewData["CampaignId"] = new SelectList(await _uow.Campaigns.AllAsync(), nameof(Campaign.CampaignId), nameof(Campaign.CampaignName));
            ViewData["CinemaId"] = new SelectList(await _uow.Cinemas.AllAsync(), nameof(Cinema.CinemaId), nameof(Cinema.CinemaName));
            ViewData["DiscountId"] = new SelectList(await _uow.Discounts.AllAsync(), nameof(Discount.DiscountId), nameof(Discount.DisccountName));
            ViewData["DiscountTypeId"] = new SelectList(await _uow.DiscountTypes.AllAsync(), nameof(DiscountType.DiscountTypeId), nameof(DiscountType.DiscountTypeName));
            ViewData["InfoTypeId"] = new SelectList(await _uow.InfoTypes.AllAsync(), nameof(InfoType.InfoTypeId), nameof(InfoType.InfoTypeName));
            ViewData["MovieId"] = new SelectList(await _uow.Movies.AllAsync(), nameof(Movie.MovieId), nameof(Movie.MovieName));
            ViewData["ProductId"] = new SelectList(await _uow.Products.AllAsync(), nameof(Product.ProductId), nameof(Product.ProductName));
            ViewData["UserGroupId"] = new SelectList(await _uow.UserGroups.AllAsync(), nameof(UserGroup.UserGroupId), nameof(UserGroup.UserGroupName));
            return View(info);
        }

        // POST: Info/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("InfoId,Description,InfoTypeId,CinemaId,MovieId,ProductId,CampaignId,UserGroupId,DiscountId,DiscountTypeId")] Info info)
        {
            if (id != info.InfoId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _uow.Info.Update(info);
                    await _uow.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!_uow.Info.Exists(info.InfoId))
                    {
                        return NotFound();

WebApp/Controllers/RowsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DAL.App.EF;
using Domain;
using DAL.App.Interfaces;

namespace WebApp.Controllers
{
    public class RowsController : Controller
    {
        private readonly IAppUnitOfWork _uow;

        public RowsController(IAppUnitOfWork uow)
        {
            _uow = uow;
        }

        // GET: Rows
        public async Task<IActionResult> Index()
        {
            //var applicationDbContext = _uow.Rows.Include(r => r.CinemaHall);
            return View(await _uow.Rows.AllAsync());
        }

        // GET: Rows/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var row = await _uow.Rows.FindAsync(id);
                //.Include(r => r.CinemaHall)
                //.SingleOrDefaultAsync(m => m.RowId == id);
            if (row == null)
            {
                return NotFound();
            }

            return View(row);
        }

        // GET: Rows/Create
        public async Task<IActionResult> Create()
        {
            //ViewData["CinemaHallId"] = new SelectList(_uow.CinemaHalls, "CinemaHallId", "CinemaHallName");
            ViewData["CinemaHallId"] = new SelectList(await _uow.CinemaHalls.AllAsync(), nameof(CinemaHall.CinemaHallId), nameof(CinemaHall.CinemaHallName));
            return View();
        }

        // POST: Rows/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("RowId,RowNumber,SeatAmount,CinemaHallId")] Row row)
        {
            if (ModelState.IsValid)
            {
                _uow.Rows.Add(row);
                await _uow.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            //ViewData["CinemaHallId"] = new SelectList(_uow.CinemaHalls, "CinemaHallId", "CinemaHallName", row.CinemaHallId);
            ViewData["CinemaHallId"] = new SelectList(await _uow.CinemaHalls.AllAsync(), nameof(CinemaHall.CinemaHallId), nameof(CinemaHall.CinemaHallName));
            return View(row);
        }

        // GET: Rows/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var row = await _uow.Rows.FindAsync(id);
            if (row == null)
            {
                return NotFound();
            }
            //ViewData["CinemaHallId"] = new SelectList(_uow.CinemaHalls, "CinemaHallId", "CinemaHallName", row.CinemaHallId);
            ViewData["CinemaHallId"] = new SelectList(await _uow.CinemaHalls.AllAsync(), nameof(CinemaHall.CinemaHallId), nameof(CinemaHall.CinemaHallName));
            return View(row);
        }

        // POST: Rows/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("RowId,RowNumber,SeatAmount,CinemaHallId")] Row row)
        {
            if (id != row.RowId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _uow.Rows.Update(row);
                    await _uow.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!_uow.Rows.Exists(row.RowId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            //ViewData["CinemaHallId"] = new SelectList(_uow.CinemaHalls, "CinemaHallId", "CinemaHallName", row.CinemaHallId);
            ViewData["CinemaHallId"] = new SelectList(await _uow.CinemaHalls.AllAsync(), nameof(CinemaHall.CinemaHallId), nameof(CinemaHall.CinemaHallName));
            return View(row);
        }

        // GET: Rows/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var row = await _uow.Rows.FindAsync(id);
                //.Include(r => r.CinemaHall)
                //.SingleOrDefaultAsync(m => m.RowId == id);
            if (row == null)
            {
                return NotFound();
            }

            return View(row);
        }

        // POST: Rows/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var row = await _uow.Rows.FindAsync(id);
            _uow.Rows.Remove(row);
            await _uow.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        //private bool RowExists(int id)
        //{
        //    return _uow.Rows.Any(e => e.RowId == id);
        //}
    }
}

WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApp</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">WebApp</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Users" asp-action="Index">Users</a></li>
                    @*<li><a asp-area="" asp-controller="UserGroups" asp-action="Index">UserGroups</a></li>
                    <li><a asp-area="" asp-controller="payments" asp-action="index">payments</a></li>
                    <li><a asp-area="" asp-controller="Orders" asp-action="Index">Orders</a></li>
                    <li><a asp-area="" asp-controller="OrderRows" asp-action="Index">OrderRows</a></li>
                    <li><a asp-area="" asp-controller="OrderRowComponents" asp-action="Index">OrderRowComponents</a></li>
                    <li><a asp-area="" asp-controller="ProductIn_OrderRowComponent" asp-action="Index">ProductsIn_OrderRowComponents</a></li>*@
                    @*<li><a asp-area="" asp-controller="Products" asp-action="Index">Products</a></li>
                    <li><a asp-area="" asp-controller="ProductGroups" asp-action="Index">ProductGroups</a></li>
                    <li><a asp-area="" asp-controller="Prices" asp-action="Index">Prices</a></li>
                    <li><a asp-area="" asp-controller="Currencies" asp-action="Index">Currencies</a></li>
                    <li><a asp-area="" asp-controller="Campaigns" asp-action="Index">Campaigns</a></li>*@
                    @*<li><a asp-area="" asp-controller="Discounts" asp-action="Index">Discounts</a></li>
                    <li><a asp-area="" asp-controller="DiscountTypes" asp-action="Index">DiscountTypes</a></li>
                    <li><a asp-area="" asp-controller="Cinemas" asp-action="Index">Cinemas</a></li>
                    <li><a asp-area="" asp-controller="CinemaHalls" asp-action="Index">CinemaHalls</a></li>
                    <li><a asp-area="" asp-controller="Rows" asp-action="Index">Rows</a></li>
                    <li><a asp-area="" asp-controller="Seats" asp-action="Index">Seats</a></li>*@
                    <li><a asp-area="" asp-controller="Movies" asp-action="Index">Movies</a></li>
                    <li><a asp-area="" asp-controller="MovieInCinemas" asp-action="Index">MovieInCinema</a></li>
                    <li><a asp-area="" asp-controller="Sessions" asp-action="Index">Sessions</a></li>
                    <li><a asp-area="" asp-controller="Tickets" asp-action="Index">Tickets</a></li>
                    <li><a asp-area="" asp-controller="Info" asp-action="Index">Info</a></li>
                    <li><a asp-area="" asp-controller="InfoTypes" asp-action="Index">InfoTypes</a></li>
                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - WebApp</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>